rvm: '2.2.1'
script:
  - bundle exec bin/rake db:create
  - bundle exec bin/rake db:migrate
  - bundle exec rspec spec

addons:
  code_climate:
    repo_token: 325cc8fafc9125c42f86a2c717468f24fbaf5276b8b1ccac805faaf39e1c835b
